### ISSUE TITLE
Error with deltalake 0.15.0 linux-64 python3.9 package

### ISSUE THREAD

**Issue by echai58** [conda-forge/deltalake-feedstock#18]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am trying to install the recently released deltalake 0.15.0 via conda-forge for linux-64 on python 3.9. I am able to install it, but it seems as if the package is empty. For example, `from deltalake import DeltaTable` is broken, and if I look at the package directory, I only see `_internal.abi3.so` instead any of the python files.

### Installed packages

```shell
deltalake
```

### Environment info

```shell
n/a
```

**Comment by digi691** [comment]
@dhirschfeld or @charlesbluca building this on my development machine with `conda build` provided a workable package for Python 3.9.  At first glance I'm unsure what the issue is with the Python 3.9 release pipeline.

**Comment by charlesbluca** [comment]
Thanks @echai58 for reporting and @digi691 for trying things out locally - might I ask what `conda build` command you tried locally? Might also be worth giving this a spin with the local build script to see if that gives any different results.

My naive guess here is that the format of the source distribution has changed such that we are no longer automatically including the python modules we require - checking the sdist as of 0.15.0, it does look like 2 copies of the modules are being published in both `deltalake/` and `python/deltalake/`, which wasn't being done before this.

As I'm not a maintainer of the main project, might be worth pinging @ion-elgreco (who cut the last two PyPI releases) to see if this change was intentional?

**Comment by ion-elgreco** [comment]
Python/deltalake is the python code for the library, python/src contains the rust lib with the bindings.

Deltalake I presume you are looking at crates/deltalake that's the rust crate.

So I am not sure where it's going wrong but we didn't make a change in the python binding in terms of the structure

**Comment by charlesbluca** [comment]
> Deltalake I presume you are looking at crates/deltalake that's the rust crate.

Nope, there is a top level `deltalake` directory in the [latest source distribution](https://files.pythonhosted.org/packages/96/26/4a5d6d700060d9c960eae5115b8b3574acf452cef21060a24c0721a11fb1/deltalake-0.15.1.tar.gz) that contains another copy of the python modules:

![image](https://github.com/conda-forge/deltalake-feedstock/assets/20627856/94fbce7b-32c3-4d87-8785-71374ac41e17)

Are these meant to be consumed in some separate way from the `python/deltalake` code? Doesn't seem like these duplicate files were present in 0.14.0 (the last working conda-forge release):

![image](https://github.com/conda-forge/deltalake-feedstock/assets/20627856/0cc1c2b2-3073-4496-90d8-03db58417f62)

**Comment by ion-elgreco** [comment]
This one I need to investigate

**Comment by digi691** [comment]
@charlesbluca I naively executed the below in the base of the project with a Python 3.9 environment activated.
`conda mambabuild recipe/`

The build produced the following files from the following artifact deltalake-0.15.1-py39h9bf148f_0.tar.bz2 which works in an python 3.9 environment.

```
.
├── deltalake-0.15.1-py39h9bf148f_0.tar.bz2
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── licenses
│   │   └── licenses
│   │       └── deltalake_license.txt
│   ├── paths.json
│   ├── recipe
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   └── test
│       ├── run_test.py
│       ├── run_test.sh
│       └── test_time_dependencies.json
└── lib
    └── python3.9
        └── site-packages
            ├── deltalake
            │   ├── data_catalog.py
            │   ├── exceptions.py
            │   ├── fs.py
            │   ├── __init__.py
            │   ├── _internal.abi3.so
            │   ├── _internal.pyi
            │   ├── __pycache__
            │   │   ├── data_catalog.cpython-312.pyc
            │   │   ├── data_catalog.cpython-39.pyc
            │   │   ├── exceptions.cpython-312.pyc
            │   │   ├── exceptions.cpython-39.pyc
            │   │   ├── fs.cpython-312.pyc
            │   │   ├── fs.cpython-39.pyc
            │   │   ├── __init__.cpython-312.pyc
            │   │   ├── __init__.cpython-39.pyc
            │   │   ├── schema.cpython-312.pyc
            │   │   ├── schema.cpython-39.pyc
            │   │   ├── table.cpython-312.pyc
            │   │   ├── table.cpython-39.pyc
            │   │   ├── _util.cpython-312.pyc
            │   │   ├── _util.cpython-39.pyc
            │   │   ├── writer.cpython-312.pyc
            │   │   └── writer.cpython-39.pyc
            │   │   └── writer.cpython-39.pyc
            │   ├── py.typed
            │   ├── schema.py
            │   ├── table.py
            │   ├── _util.py
            │   └── writer.py
            └── deltalake-0.15.1.dist-info
                ├── direct_url.json
                ├── INSTALLER
                ├── license_files
                │   └── deltalake_license.txt
                ├── METADATA
                ├── RECORD
                ├── REQUESTED
                └── WHEEL
```

I then ran the following script `python build-locally.py linux_64_python3.9.____cpython` which produced `deltalake-0.15.1-py39hccdef0e_0.conda` with the following contents matching what we see from the downloaded package from the conda-forge channel:

```
╰─ tree
.
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── licenses
│   │   └── licenses
│   │       └── deltalake_license.txt
│   ├── paths.json
│   ├── recipe
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   ├── meta.yaml.template
│   │   └── recipe-scripts-license.txt
│   └── test
│       ├── run_test.py
│       ├── run_test.sh
│       └── test_time_dependencies.json
└── lib
    └── python3.9
        └── site-packages
            ├── deltalake
            │   └── _internal.abi3.so
            └── deltalake-0.15.1.dist-info
                ├── direct_url.json
                ├── INSTALLER
                ├── license_files
                │   └── deltalake_license.txt
                ├── METADATA
                ├── RECORD
                ├── REQUESTED
                └── WHEEL
```

**Comment by jakirkham** [comment]
How does that build environment compare to [the one used on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=854394&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=55f066f8-9d52-54c8-1ae3-a2d9002ff304&l=185 )?

**Comment by jakirkham** [comment]
Also @echai58 could you please fill out [the full issue template]( https://github.com/conda-forge/.github/blob/main/.github/ISSUE_TEMPLATE/1-bug-report.yml ) with a minimal reproducer?

This would really go a long way towards helping us resolve the issue

**Comment by charlesbluca** [comment]
Was able to reproduce with the 3.12 linux-64 packages:

```
conda create -n test-deltalake-0150 -c conda-forge deltalake=0.15.0
conda activate test-deltalake-0150
python -c "from deltalake import DeltaTable"
```

I suspect this issue is present in all the linux-64 packages for `>=0.15.0`, and probably the other platforms as well (though I haven't had the chance to check, not sure how to inspect `.conda` packages outside of installing). Here's the environment info:

`conda list`:

<details>

```
# packages in environment at /raid/charlesb/miniforge3/envs/test-deltalake-0150:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aws-c-auth                0.7.11               h0100c56_0    conda-forge
aws-c-cal                 0.6.9                h5d48c4d_2    conda-forge
aws-c-common              0.9.10               hd590300_0    conda-forge
aws-c-compression         0.2.17               h7f92143_7    conda-forge
aws-c-event-stream        0.4.1                h0bcb0bb_1    conda-forge
aws-c-http                0.8.0                hd268abd_1    conda-forge
aws-c-io                  0.13.36              hb3b01f7_3    conda-forge
aws-c-mqtt                0.10.0               hf5d392a_2    conda-forge
aws-c-s3                  0.4.7                hf8c57b3_3    conda-forge
aws-c-sdkutils            0.1.13               h7f92143_0    conda-forge
aws-checksums             0.1.17               h7f92143_6    conda-forge
aws-crt-cpp               0.26.0               h600aa22_5    conda-forge
aws-sdk-cpp               1.11.210             h405b101_9    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.25.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
deltalake                 0.15.0          py312hd892df0_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libarrow                  14.0.2           h84dd17c_2_cpu    conda-forge
libarrow-acero            14.0.2           h59595ed_2_cpu    conda-forge
libarrow-dataset          14.0.2           h59595ed_2_cpu    conda-forge
libarrow-flight           14.0.2           h120cb0d_2_cpu    conda-forge
libarrow-flight-sql       14.0.2           h61ff412_2_cpu    conda-forge
libarrow-gandiva          14.0.2           hacb8726_2_cpu    conda-forge
libarrow-substrait        14.0.2           h61ff412_2_cpu    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libgoogle-cloud           2.12.0               h5206363_4    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.9.0                hd590300_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libparquet                14.0.2           h352af49_2_cpu    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.3          py312heda63a1_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
orc                       1.9.2                h4b38347_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2          py312h176e3d2_2_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
python                    3.12.1          hab00c5b_1_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
rdma-core                 49.0                 hd3aeb46_2    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.4.1                h06160fa_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucx                       1.15.0               h75e419f_2    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

</details>

`conda info`:

<details>

```

     active environment : test-deltalake-0150
    active env location : /raid/charlesb/miniforge3/envs/test-deltalake-0150
            shell level : 2
       user config file : /home/nfs/charlesb/.condarc
 populated config files : /raid/charlesb/miniforge3/.condarc
                          /home/nfs/charlesb/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.12.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=broadwell
                          __conda=23.11.0=0
                          __cuda=12.0=0
                          __glibc=2.31=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /raid/charlesb/miniforge3  (writable)
      conda av data dir : /raid/charlesb/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /raid/charlesb/miniforge3/pkgs
                          /home/nfs/charlesb/.conda/pkgs
       envs directories : /raid/charlesb/miniforge3/envs
                          /home/nfs/charlesb/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.12 Linux/5.4.0-159-generic ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.6
                UID:GID : 10232:10004
             netrc file : None
           offline mode : False



```

</details>

**Comment by digi691** [comment]
> How does that build environment compare to [the one used on CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=854394&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=55f066f8-9d52-54c8-1ae3-a2d9002ff304&l=185)?

The environment I used for the working package is my default miniconda installation (base) with conda-build installed on my x86-64 Linux development machine.  Nothing special... The incomplete package from briefly reading the installation script is using a conda-forge docker image and their CI scripts.  I guess all that I've showed is that the recipe file may be correct, and something is missing for the conda-forge CI to pick up and package the artifacts appropriately in that CI container.

**Comment by digi691** [comment]
> Was able to reproduce with the 3.12 linux-64 packages:
> 
> ```
> conda create -n test-deltalake-0150 -c conda-forge deltalake=0.15.0
> conda activate test-deltalake-0150
> python -c "from deltalake import DeltaTable"
> ```
> 
> I suspect this issue is present in all the linux-64 packages for `>=0.15.0`, and probably the other platforms as well (though I haven't had the chance to check, not sure how to inspect `.conda` packages outside of installing). Here's the environment info:
> 
> `conda list`:
> 
> `conda info`:

I believe `cph` will extract .conda files.  https://anaconda.org/anaconda/conda-package-handling

**Comment by jakirkham** [comment]
> > How does that build environment compare to [the one used on CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=854394&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=55f066f8-9d52-54c8-1ae3-a2d9002ff304&l=185)?
> 
> The environment I used for the working package is my default miniconda installation (base) with conda-build installed on my x86-64 Linux development machine. Nothing special... The incomplete package from briefly reading the installation script is using a conda-forge docker image and their CI scripts. I guess all that I've showed is that the recipe file may be correct, and something is missing for the conda-forge CI to pick up and package the artifacts appropriately in that CI container.

Could you please create a diff between the two environments (yours that works and CI)? We would like to identify any differences

**Comment by elveshoern32** [comment]
Hi folks,

the 0.15.1 package at conda-forge is still broken (for me, i.e. Linux, deltalake-0.15.1-py312hd892df0_0.conda).
'polars' suffered from apparently the same problem.
Please look at
https://github.com/conda-forge/polars-feedstock/issues/205
and
https://github.com/conda-forge/conda-smithy/issues/1827

**Comment by charlesbluca** [comment]
Thanks for the context @elveshoern32! Looks like this issue should be resolved with #20 if anyone else would like to verify locally.

Beyond that, might be worth keeping our eyes on https://github.com/PyO3/maturin/issues/1911 to see if any changes are made to maturin to reflect this.

**Comment by echai58** [comment]
@charlesbluca 0.15.1 is working for me now :tada: i think 0.15.0 will still be broken, (don't see that updated today here: https://anaconda.org/conda-forge/deltalake/files), if that's a concern.

**Comment by charlesbluca** [comment]
Thanks @echai58 :tada: the broken 0.15.0 packages aren't a problem for my use cases, unless there's a specific need to backport the fix I'm satisfied with marking those packages as broken

**Comment by echai58** [comment]
> Thanks @echai58 🎉 the broken 0.15.0 packages aren't a problem for my use cases, unless there's a specific need to backport the fix I'm satisfied with marking those packages as broken

@charlesbluca same for me, thanks for helping with this!

**Comment by ion-elgreco** [comment]
> Thanks @echai58 🎉 the broken 0.15.0 packages aren't a problem for my use cases, unless there's a specific need to backport the fix I'm satisfied with marking those packages as broken

There is actually an issue with 0.15.1 atm, during some refactors, and pushing a release to soon the GCP support got dropped. So could be useful to still get 0.15.0 in the conda feed.

**Comment by dhirschfeld** [comment]
Resolved by #20
